version: 2.1

services:
  db:
    image: mysql
    env:
      - MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:3.2
  web:
    build: .
    command: python /var/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
