version: '2.1'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:3.2
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: celery worker --app factorio_manager.celery:app --loglevel=INFO
    depends_on:
      - db
      - redis
